# Generated by Django 5.0.7 on 2024-07-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(default='https://github.com/aminjoncls01?tab=repositories'),
        ),
    ]
